### ISSUE TITLE
It is mentioned not to use wagtail demo for starting a site. Are there any security risks?

### ISSUE THREAD

**Issue by igauravsehrawat** [torchbox/wagtaildemo#104]
Is it just the lack of best practices or any vulnerable issues for such mention?

Thanks

**Comment by gasman** [comment]
Hi @igauravsehrawat - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

**Comment by igauravsehrawat** [comment]
@gasman Yeah, my bad. I forgot.
