### ISSUE TITLE
Debian install script failing on new v7 box

### ISSUE THREAD

**Issue by chrxr** [torchbox/wagtaildemo#38]
Running the Debian one-liner on a new, clean Debian 7 box with Digital Ocean.
(curl -O https://wagtail.io/debian.sh; bash debian.sh)

Script gets all the way through, but can't access Wagtail demo at the IP when finished.

Installing with default project name and project location.

Only error I can see is right at the end with uwsgi:

    Successfully installed uwsgi
	Cleaning up...
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	100   623  100   623    0     0   9382      0 --:--:-- --:--:-- --:--:-- 18878
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	chmod: cannot access `/etc/init.d/uwsgi': No such file or directory
	update-rc.d: using dependency based boot sequencing
	update-rc.d: error: unable to read /etc/init.d/uwsgi
	uwsgi: unrecognized service
	Restarting nginx: nginx.

	Wagtail lives!

	The public site is at http://107.170.78.41/
	and the admin interface is at http://107.170.78.41/admin/

**Comment by gasman** [comment]
Closing as these scripts are no longer supported.
