### ISSUE TITLE
django_libsass.SassCompiler: not found

### ISSUE THREAD

**Issue by rajasimon** [torchbox/wagtaildemo#39]
I am not using vagrant and postgres 

And i manage to install every dependencies which need to run wagtail

And successful migration after running localhost i am getting this error  

> /bin/sh: 1: django_libsass.SassCompiler: not found

I pasted the copy of pip freeze output here. See i having 

Django==1.6.5
Pillow==2.5.2
South==1.0
Unidecode==0.04.16
argparse==1.2.1
beautifulsoup4==4.3.2
compass==0.1.4
django-appconf==0.6
django-compressor==1.4
django-libsass==0.2
django-modelcluster==0.3
django-taggit==0.12.1
django-treebeard==2.0
html5lib==0.999
psycopg2==2.5.3
requests==2.3.0
six==1.7.3
unicodecsv==0.9.4
wagtail==0.5
wsgiref==0.1.2

If you need Full traceback please [click here](https://gist.github.com/rajasimon/53ae692050b998f3abe8)

**Comment by tezro** [comment]
It's still relevant. Doesn't work within virtual environment.

**Comment by gasman** [comment]
@tezro If you're having problems, please open a new issue with a full description of your setup and the installation steps you've taken.

**Comment by tezro** [comment]
Well, to be honest, the setup is absolutely the same: pip install django-libsass libsass runs without problems, but Django is raising "/bin/sh: django_libsass.SassCompiler: command not found" for any version of each of them...

**Comment by gasman** [comment]
If `pip freeze` shows that libsass is successfully installed, then the problem is different to the one discussed on this ticket. Without a full description of that problem, I can't really help any further.

**Comment by gasman** [comment]
I've now put together a wiki page detailing steps to try when encountering this error: [Troubleshooting `/bin/sh: django_libsass.SassCompiler: command not found`](https://github.com/torchbox/django-libsass/wiki/Troubleshooting)
