### ISSUE TITLE
db migratation failed with SQLite as backend

### ISSUE THREAD

**Issue by kidlj** [torchbox/wagtaildemo#49]
```

Operations to perform:
  Synchronize unmigrated apps: modelcluster, wagtailsnippets, compressor
  Apply all migrations: wagtaildocs, wagtailadmin, wagtailcore, wagtailredirects, auth, wagtailforms, wagtailembeds, demo, wagtailusers, wagtailsearch, taggit, wagtailimages, contenttypes, sessions, admin
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying demo.0001_initial...Traceback (most recent call last):
  File "/home/mellon/Wagtail/venv/lib/python3.3/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mellon/Wagtail/venv/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table demo_blogpage__new has no column named tags

```

**Comment by gasman** [comment]
Hi @kidlj,
Unfortunately Django 1.7.2 introduced a regression that broke the `taggit` library on Sqlite - see https://github.com/alex/django-taggit/issues/285. For now, I suggest downgrading Django to 1.7.1 until a fix is available - I've now made this change to wagtaildemo's dependencies, in 41f0620b206e591ce8dc0d0bacb03ac1b2bd197a.

**Comment by zerolab** [comment]
Django 1.7.4 was released. It should have the fix for the above issue.
See https://docs.djangoproject.com/en/dev/releases/1.7.4/

**Comment by gasman** [comment]
@zerolab If 1.7.4 is still failing, it sounds like we need to wait for a new version of django-taggit with https://github.com/alex/django-taggit/pull/286 applied.

**Comment by Kashyab19** [comment]
How to downgrade in Windows? @gasman

**Comment by gasman** [comment]
@Kashyab19 This issue is more than 4 years old, and Django 1.7.x is no longer supported - whatever problem you're having, I can guarantee that downgrading to Django 1.7.1 is not the solution.
