### ISSUE TITLE
Deploy to Heroku Error

### ISSUE THREAD

**Issue by klummy** [torchbox/wagtaildemo#50]
I used the "Deploy to Heroku" button to try out the wagtaildemo but received this error:
*Run scripts & scale dynos
There was an issue while running the post deploy script:*

![screenshot from 2015-01-30 06 20 12](https://cloud.githubusercontent.com/assets/4457871/5971530/17366968-a848-11e4-8cba-00d6dbad6d9c.png)

**Comment by spapas** [comment]
@klummy you are right, deploying to Heroku doesn't work :(

@kaedroho this is because there's a bunch of required mongo settings in settings/heroku.py (to store files). This section probably needs to be optional (if a MONGODB_NAME env var exists only then setup mongo).

**Comment by kaedroho** [comment]
Oops, I was messing around with storing files in MongoDB last night. I must've accidentally pushed.

Sorry about that, will rollback/

**Comment by kaedroho** [comment]
I've rollbacked all the mongodb stuff now. Kept the Heroku PR merged since I think it's in a good enough state to start using now anyway.

**Comment by klummy** [comment]
It is working now. Thanks Kaedroho.

**Comment by klummy** [comment]
Quick question, how do I create a superuser?

**Comment by spapas** [comment]
@klummy a superuser is created by default with the credentials admin / changeme (https://github.com/torchbox/wagtaildemo#installation)

**Comment by klummy** [comment]
Ok, thanks spapas
