### ISSUE TITLE
django-treebeard version bump

### ISSUE THREAD

**Issue by shacker** [torchbox/wagtaildemo#57]
Using the demo setup instructions (in a virtualenv with python 3.4), I got:

```
$ ./manage.py load_initial_data
/Users/shacker/Sites/virtualenvs/wagtaildemo/lib/python3.4/site-packages/treebeard/mp_tree.py:102: RemovedInDjango18Warning: `MP_NodeManager.get_query_set` method should be renamed `get_queryset`.
  class MP_NodeManager(models.Manager):
```

I noticed there was a later version of treebeard available, and  was able to solve this with:

```
pip uninstall django-treebeard
pip install django-treebeard==3.0
```

I was then able to :

`./manage.py load_initial_data`

and run the app successfully.

**Comment by gasman** [comment]
Hi @shacker - thanks for the report. We've upgraded the version of Treebeard for the next major release of Wagtail (0.9), and we'll update wagtaildemo accordingly when we release it.

(Treebeard 3.0 drops support for Python 2.6 and Django 1.6, which Wagtail 0.8 is still officially supporting, so we can't make this change just yet - but in the meantime these warnings are harmless and can be ignored.)
