### ISSUE TITLE
AttributeError at /search/

### ISSUE THREAD

**Issue by shacker** [torchbox/wagtaildemo#58]
The demo includes a search field at top right, but typing in a search term or accessing /search directly errors with:

```
AttributeError at /search/
'str' object has no attribute 'url'
```

on template line:

`{% top_menu parent=site_root calling_page=self %}`

stack trace points to demo/templatetags/demo_tags.py :

```
        menuitem.active = (False if calling_page is None
                           else calling_page.url.startswith(menuitem.url))
```

I changed that to 

`        menuitem.active = False`

Just to keep the demo running, but needs a better fix.

**Comment by gasman** [comment]
It turns out this bug was already fixed in #54 which is awaiting review/merging, so I've now merged in the commit that fixes this. (8fbcda1621eb3924759d8c376888aad6b68537d7)
