### ISSUE TITLE
Need to run collectstatic everytime that I change .scss?

### ISSUE THREAD

**Issue by dudunato** [torchbox/wagtaildemo#61]
I'm testing wagtaildemo and everytime that I change a .scss file I need to run collectstatic, is that right? How can I workaround this?

**Comment by gasman** [comment]
Hi @dudunato,
Please use the [Google group](https://groups.google.com/forum/#!forum/wagtail) for support questions.

**Comment by dudunato** [comment]
Hi @gasman 

Sorry! I'll do it.

Thanks

**Comment by dudunato** [comment]
Hi @gasman,

Please, could you help me with this? https://groups.google.com/forum/#!topic/wagtail/02JvSbnTbGY

:smiley:
