### ISSUE TITLE
More dependencies

### ISSUE THREAD

**Issue by oyvindsk** [torchbox/wagtaildemo#7]
Just FYI, on Fedora 20 I also had to install:

* postgresql *- Not planning on using it, but the installer complained*
* postgresql-devel  *- Could not find libpq-fe.h*
* python-devel *- Could not find Python.h*
* libxml2-devel *- Could not find libxml/xmlversion.h*
* libxslt-devel *- ditto*

Wagtail looks cool.. If I can get it to run, I'll make a docker image

**Comment by BertrandBordage** [comment]
As I did [in my wagtail-demo Docker image](https://registry.hub.docker.com/u/bbordage/wagtail-demo/dockerfile/), Pillow dependencies can easily be installed in Ubuntu using build-dep.

So a minimal command would be (using Ubuntu 14.10):
```bash
sudo apt-get install postgresql postgresql-server-dev-9.4 build-essential python-pip python-dev
sudo apt-get build-dep pillow
```

**Comment by gasman** [comment]
libxml and libxslt are no longer required, and Postgres is mentioned as a dependency in the readme. I don't think we should be listing specific postgres-related packages - we can't support every possible configuration, and people who are not going down the Vagrant route (or another third-party prebuilt one) are expected to have a certain amount of background knowledge about setting up Python / Django environments. The Wagtail documentation no longer suggests installing wagtaildemo as a starting point for new users, so I think everything here is now accounted for.
