### ISSUE TITLE
No StreamField-love in the demo

### ISSUE THREAD

**Issue by spoetnik** [torchbox/wagtaildemo#76]
I can't find a reference to the StreamField in the demo.

This is a seller-feature for wagtail, so I would have expected some reference to this.

**Comment by davecranwell** [comment]
Yes sorry about that @spoetnik, it's now a PR awaiting merge here, if you're interested: https://github.com/torchbox/wagtaildemo/pull/81

(requires a clean database first)

**Comment by gasman** [comment]
Fixed in #81.
