### ISSUE TITLE
PATH_TO_WAGTAIL in settings/local.py ignored

### ISSUE THREAD

**Issue by waldo90** [torchbox/wagtaildemo#79]
settings/base.py import wagtail at line 173 thereby invalidating any following PATH_TO_WAGTAIL in settings/local.py.

Might it be better to drop PATH_TO_WAGTAIL and instead have a pip requirements for wagtail development that installs direct from github? E.g:

-e git+https://github.com/torchbox/wagtail.git@torchbox#egg=wagtail==1.1a0

**Comment by gasman** [comment]
If you run `python ./setup.py develop` on the checked-out Wagtail codebase, does that fix the problem?

(I have that step as part of my own install script <https://github.com/gasman/vagrant-wagtail-develop>, and haven't encountered any problems - it may be that this actually eliminates the need for the PATH_TO_WAGTAIL setting. Will update the installation docs if so...)

**Comment by waldo90** [comment]
Excellent - that fixed it - thanks Matt

**Comment by gasman** [comment]
Having re-tested this, it looks like the developer docs need a more extensive rewrite - in particular, the development copy of the wagtail repo is not usable at all until the npm static file building stuff is in place, which is much further down the instructions. I'll get on to this shortly.

**Comment by gasman** [comment]
Improved docs now submitted in https://github.com/torchbox/wagtail/pull/1759, and PATH_TO_WAGTAIL stuff being removed in #82.
