### ISSUE TITLE
SQLite instructions need improving

### ISSUE THREAD

**Issue by chris-morgan** [torchbox/wagtaildemo#80]
The instructions in the README say SQLite3 is fine, just change ENGINE. But NAME is set to 'wagtaildemo', which will cause it to try to work with `./wagtaildemo` as its database file, and that will be the app directory. The instructions should say something like “and add a `.sqlite` suffix to the `NAME` (to avoid a clash with the directory name)”.

**Comment by gasman** [comment]
Thanks for pointing this out! Fixed in fb3f444a67a690d574687b2e71c29cb40cb64429.
