### ISSUE TITLE
Error when installing requirements

### ISSUE THREAD

**Issue by Bokdem** [torchbox/wagtaildemo#85]
I've cloned this repo to checkout the wagtail demo locally. Whenever i try to run the pip install -r requirements.txt i get the following error.

```shell
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7f/cjzthrfs7n96m12kkhfkdb7c0000gn/T/pip-build-Wn7MN7/psycopg2

**Comment by gasman** [comment]
Hi @Bokdem - it sounds like you're probably missing the `python-dev` or `libpq` dependencies required by psycopg2 (although we'd need to see more of the error messages to be sure). Please see http://initd.org/psycopg/docs/install.html#install-from-source

**Comment by Bokdem** [comment]
That was missing indeed. Kind of new to these backend things so the README is kind of a unclear to me, im sorry. Running into this next error:
```shell
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

I guess postgres configuration is wrong?

**Comment by gasman** [comment]
It sounds like it, yes. I'd suggest using the Vagrant setup instructions, as these provide a predictable/consistent Postgres setup - the non-Vagrant setup assumes some familiarity with Django and Postgres, and we aren't able to provide support for configuring Postgres.

**Comment by Bokdem** [comment]
Yes, will make use of the Vagrant setup. Everything works fine now. Thanks for the support! :)
