### ISSUE TITLE
Fail installing packages without Postgresql

### ISSUE THREAD

**Issue by Talkerbox** [torchbox/wagtaildemo#93]
When I use SQLite as an alternative to PostgeSQL, I mean than I haven't this DB in my system. So, in my case I just commented string with psycopg2 in _requirements.txt_ before the run `pip install` command. It was help for me, but it will be good, if you add this stem to README

**Comment by gasman** [comment]
Thanks @Talkerbox! I've updated the instructions in 90b0ef877d8955945842bc1f3684e2cb3343ec89.
