### ISSUE TITLE
StreamField issue

### ISSUE THREAD

**Issue by mronoffon** [torchbox/wagtaildemo#95]
I get 'ValueError: invalid literal for int() with base 10: '' ' ,whenever I try to post using a StreamField.

the error occurs at:  File "/opt/python27/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 159, in value_from_datadict

Using the latest version of wagtail/django

**Comment by gasman** [comment]
Hi @mronoffon,
This is working fine for me on a new install of wagtaildemo - please can you list the exact steps you're taking, starting from a clean install?

The steps I'm taking are:
* Install as per https://github.com/torchbox/wagtaildemo#installation
* Go to http://localhost:8000/admin/ , log in as `admin` / `changeme`
* From the left menu, Explorer -> Home page -> Add child page -> Blog page
* Fill in the fields as follows:
    * title: test
    * post date: 2016-07-28
    * body: add an intro with text 'test'
* Click 'save draft' - the page saves as expected, with no errors

Some other details that would be useful to know:
* your browser version
* any errors that appear in the browser's Javascript console
* the full text of the error page. (In particular, it would be useful to see the POST data shown under "Request information" here)

(By the way - it's best to mention the specific version numbers of Wagtail / Django you're using. Saying "the latest version" won't be meaningful if we need to revisit this bug report after a few months...)
