### ISSUE TITLE
top_menu

### ISSUE THREAD

**Issue by waytai** [torchbox/wagtaildemo#97]
in demo/templatetags  top_menu
if the variable calling_page is str ,there will generate error

**Comment by gasman** [comment]
@waytai As far as I can see, `top_menu` is only ever called [here](https://github.com/torchbox/wagtaildemo/blob/e73170a1ac4eb30f1a071e81542b21c136ced1cd/demo/templates/demo/base.html#L54), and `self` will never be a string. Can you give an example of where this is failing?

**Comment by waytai** [comment]
@gasman  sorry , my worry is unnecessay
